"""v1

Revision ID: e6fb48fef9be
Revises: 6d266bdb1a9c
Create Date: 2022-09-27 18:26:53.884699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fb48fef9be'
down_revision = '6d266bdb1a9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
